version: "3.8"
services:
  postgres:
    container_name: rinha-postgres
    image: postgres:latest
    hostname: db-rinha
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
